### ISSUE TITLE
fresnel typo

### ISSUE THREAD

**Issue by gsimone** [pmndrs/lamina#1]
it's wrote as fresnal, should be fresnel

**Comment by FarazzShaikh** [comment]
Good looking out, thanks! Fixed!

**Comment by CodyJasonBennett** [comment]
Same with uniform in various forms:

![image](https://user-images.githubusercontent.com/23324155/151829661-16af2a78-f69f-4385-bf6c-2875472f7828.png)

**Comment by FarazzShaikh** [comment]
Fixed
