### ISSUE TITLE
Changing blend mode in newly added layer breaks the shaders in the sandbox example

### ISSUE THREAD

**Issue by yokiano** [pmndrs/lamina#12]
How to replicate - 
in the sandbox example with Suzanne (https://4tdfb.sse.codesandbox.io/) - Just add a new layer and change the blend mode. 
I see also that the blend modes are all CAPITAL letters in contrast with the existing layers. so it is maybe a lead to culprit.

Attaching a file with the console error log. 
[4tdfb.sse.codesandbox.io-1644904640442.log](https://github.com/pmndrs/lamina/files/8066223/4tdfb.sse.codesandbox.io-1644904640442.log)

**Comment by FarazzShaikh** [comment]
That is probably an outdated sandbox, the latest Configurator example is [here](https://codesandbox.io/embed/github/pmndrs/lamina/tree/main/examples/example-configurator)
