### ISSUE TITLE
Module not found: Can't resolve 'react-dom/client'

### ISSUE THREAD

**Issue by robksawyer** [pmndrs/lamina#22]
Getting the following when trying to load the package in NextJS.

![Screen Shot 2022-04-04 at 2 59 25 AM](https://user-images.githubusercontent.com/179419/161441557-3e15ab1d-b13e-4570-903c-960a9ea7d094.png)

**Comment by drcmda** [comment]
are you using react 18?

**Comment by robksawyer** [comment]
Just found https://github.com/pmndrs/lamina/issues/21. I downgraded and that did the trick.
