### ISSUE TITLE
Skinned Meshes stop working with Lamina

### ISSUE THREAD

**Issue by alejandromizraji** [pmndrs/lamina#30]
Skinned meshes stop working when using Lamina. I think it might be because the shader is not implementing skinned meshes maybe?

Example without lamina:

![Screen Shot 2022-04-16 at 19 26 13](https://user-images.githubusercontent.com/10290181/163693191-2c663b4e-67c6-48d5-b764-057352ff0799.png)

![Screen Shot 2022-04-16 at 19 26 05](https://user-images.githubusercontent.com/10290181/163693185-2cae3334-33c8-480d-8c4d-17ceb06e64c6.png)

When i add Lamina:

![Screen Shot 2022-04-16 at 19 26 27](https://user-images.githubusercontent.com/10290181/163693217-b70e9fb0-55cd-45e7-a2c0-e87bba85e9db.png)

![Screen Shot 2022-04-16 at 19 26 35](https://user-images.githubusercontent.com/10290181/163693219-afad8ff5-f415-4957-af1a-8393875bf3e7.png)

**Comment by FarazzShaikh** [comment]
Hey! Can you make a sandbox of your code? Also, what version of Lamina are you using?

**Comment by alejandromizraji** [comment]
Hi! Sure!

I am using version 1.1.13 of lamina.

Here is an example using a drei example but applying lamina material. If you add a different material other than lamina it works.

https://codesandbox.io/s/skinned-mesh-nlamina-forked-2yew8d?file=/src/Model.js:2140-2145

**Comment by FarazzShaikh** [comment]
fixed via `1.1.15` 

https://codesandbox.io/s/skinned-mesh-nlamina-forked-km9y9e

**Comment by alejandromizraji** [comment]
@FarazzShaikh Thanks, man! so fast, awesome work you are doing with this lib!
