### ISSUE TITLE
three-custom-shader-material 3.5.3 'csm_Normal' undeclared identifier

### ISSUE THREAD

**Issue by Wambosa** [pmndrs/lamina#41]
**Warn:** The `three-custom-shader-material` dependency does not work when it is updated to `3.5.3`.
The examples use `"three-custom-shader-material": "3.3.6"` successfully, so that may be required to keep this stable.
Root Issue here: https://github.com/FarazzShaikh/THREE-CustomShaderMaterial/issues/22

In my own `package.json`, I added this to the dependencies:
```
    "three": "^0.139.1",
    "three-custom-shader-material": "3.3.6",
```
and then this wonderful lib began to work as expected!

Thank you for your efforts in making shader work much easier <3

**Comment by FarazzShaikh** [comment]
Thanks for the kindness, i have fixed and bumped CSM, `1.1.21` should work now
