### ISSUE TITLE
How can I apply different shading on LayerMaterial ?

### ISSUE THREAD

**Issue by bufffun** [pmndrs/lamina#7]

**Comment by FarazzShaikh** [comment]
Please elaborate on what you mean by shading

**Comment by bufffun** [comment]
Excuse my wording, maybe Lighting is more appropriate, just like Spline, it is Lighting Layer like Phong, Physic, Toon...

**Comment by FarazzShaikh** [comment]
Lighting is quite complex, I’d like to add those layers in a future update

As it stands you can use other TheeeJS materials or my [Custom Shader Material](https://github.com/FarazzShaikh/THREE-CustomShaderMaterial) to get those shading effects.

**Comment by bufffun** [comment]
Thanks for your reply! Is there a way to mix those made layer or effect into ThreeJS materials, for example,  MeshPhysicalMaterial + Fresnel Layer effect(in this repo).
Anyway, looking forward to your future update, great Job!!!!

**Comment by FarazzShaikh** [comment]
Thanks!

You should in theory be able to just copy and paste the physical material shader code into your own custom layer, after making a few modifications based on the way Lamina expects custom layers to behave, it should work.

I’ll probably do the same thing when we do bring the shading layers to Lamina.
